name: Jave CI/CD pipeline with Maven

on:
  push:
    branches: [master]
    
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          
      - name: buildtP
        run: mvn -B clean install --file pom.xml
  
      - name: upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: example_maven
          path: target/*.jar

      - name: login to heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: sample-app-catsup1
        run: heroku plugins:install java && heroku deploy:jar target/protobootapp-0.0.1-SNAPSHOT.jar --jdk 11 -Dserver.port=$PORT --app $HEROKU_APP_NAME
