name: Jave CI/CD pipeline with Maven

on:
  push:
    branches: [master]
    
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '11'

  
